[info]
description = "Backprop over economic production chains, use for socioeconomic modeling. Try to compare backprop weight to real world salary / wealth."
repo_link   = ""
tags        = ["DAG", "Democracy", "Production", "Money", "ML"]
builds_on   = []

# Scores are integers [1, 10]. Higher always means more of that thing.
# Uncomment and fill; an unscored project cannot be ranked.
[attributes]
research_topic = 10 # in my realm of research interest
research_skill = 7  # develops research skills I want
research_value = 8  # how valuable is this research work
code_topic     = 6  # in my realm of technical interest
code_skill     = 6  # develops coding skills I want
code_value     = 5  # how valuable is this code tool
boundedness    = 3  # how well-scoped
quick_v1       = 6  # how fast to first working version
low_upkeep     = 7  # how easy to maintain once working
eagerness      = 8  # how excited am I to work on it
