[info]
description = "TUI nonogram app."
repo_link   = ""
tags        = ["tui", "games"]
builds_on   = []

# Scores are integers [1, 10]. Higher always means more of that thing.
# Uncomment and fill; an unscored project cannot be ranked.
[attributes]
research_topic = 1 # in my realm of research interest
research_skill = 2 # develops research skills I want
research_value = 1 # how valuable is this research work
code_topic     = 4 # in my realm of technical interest
code_skill     = 7 # develops coding skills I want
code_value     = 3 # how valuable is this code tool
boundedness    = 9 # how well-scoped
quick_v1       = 9 # how fast to first working version
low_upkeep     = 9 # how easy to maintain once working
eagerness      = 7 # how excited am I to work on it
