[info]
description = "Art project that displays an infinite feed from a new account on one of the large social media sites, like YouTube, TikTok, or Instagram."
repo_link   = ""
tags        = ["Art", "Social Media"]
builds_on   = []

# Scores are integers [1, 10]. Higher always means more of that thing.
# Uncomment and fill; an unscored project cannot be ranked.
[attributes]
research_topic = 2 # in my realm of research interest
research_skill = 2 # develops research skills I want
research_value = 2 # how valuable is this research work
code_topic     = 3 # in my realm of technical interest
code_skill     = 4 # develops coding skills I want
code_value     = 3 # how valuable is this code tool
boundedness    = 8 # how well-scoped
quick_v1       = 8 # how fast to first working version
low_upkeep     = 7 # how easy to maintain once working
eagerness      = 4 # how excited am I to work on it
